name: PyTest

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install poetry
        run: |
          python -m pip install --upgrade poetry

      - name: Install dependencies
        run: |
          poetry install --dev

      - name: Run test suite
        run: |
          pytest
