name: PyTest


on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create and load virtual environment
        run: |
          python -m pip install poetry
          poetry install

      - name: Run test suite
        run: |
          . $(poetry env info -p)/bin/activate
          pytest --cov=demo_client --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          verbose: true

      - name: Lint with flake8
        run: |
          . $(poetry env info -p)/bin/activate
          flake8 .
