name: PyTest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create and load virtual environment
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          . ./venv/bin/activate
          python -m pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Run test suite
        run: |
          pytest --cov=demo_client --cov-report=xml --cov-report=html

      - name: Lint with flake8
        run: |
          flake8 .
